id: I2D2FC16E
ocr_import_info:
  timestamp: '2023-09-27T14:27:17.642259+00:00'
  batch_id: batch-71a9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 14:45:37.393720+00:00
last_modified: 2023-09-27 14:45:37.393727+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3282
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3282
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་འགྲེལ་གྱི་བསྟན་བཅོས་ཐུབ་བསྟན་ནོར་བུའི་གཏེར་མཛོད་ལས་གནས་དང་པོ།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9664970414311582
  ocr_word_median_confidence_index: 0.99879598
bases:
  I1NLM3282_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3282_001
      total_pages: 214
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3282_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99879598
      ocr_word_mean_confidence_index: 0.9664970414311582
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
